### ISSUE TITLE
Should SkipExtension be named SkipExtension?

### ISSUE THREAD

**Issue by pamil** [FriendsOfBehat/ExcludeSpecificationsExtension#11]
#9 got me thinking and it looks like "Skip" part in SkipExtension might be misleading, as defined features aren't **skipped** during testing, but **excluded** from the test suite.

I propose something like ExcludeExtension, although it is still not as specific as I would like it to be (what about ExcludeFeaturesExtension?).

Should we rename it?

**Comment by Zales0123** [comment]
`ExcludeFeaturesExtension` is not bad, but after adding support for [Behat CLI syntax](https://github.com/FriendsOfBehat/SkipExtension/issues/5) (already working on this) we will be able to skip also specific scenarios, rather than features 😄  So then this name will be misleading... hmm...

> Some rabbis say yes, and some rabbis say no

**Comment by pamil** [comment]
Behat uses the "specification" term, so `ExcludeSpecificationsExtension` may be appropriate.
