### ISSUE TITLE
Add '--strict' flag respect

### ISSUE THREAD

**Issue by lchrusciel** [FriendsOfBehat/ExcludeSpecificationsExtension#9]
In #8 job with skipped scenario will pass the test(see [here](https://github.com/FriendsOfBehat/SkipExtension/pull/8/files#diff-d2051aecdf9cda3c350d04412d89db91R48)) I think it should be configurable with a `strict` flag to decide if skipped scenarios should fail the whole test.

**Comment by Zales0123** [comment]
Well, this is not exactly skipped scenario - this scenario is not even taken to `test` function. So I don't think that `--strict` flag would do anything in that case.

**Comment by pamil** [comment]
The Behat run inside Behat is already run with `--strict`, in fact skipping features with #8 does not mark tests are skipped.

Please reopen if @Zales0123 or me are missing something with :tada:
